MockMDS/README.md
MockMDS/files/MockMDS/DeviceInfoFACE.txt
MockMDS/files/MockMDS/DeviceInfoFIR.txt
MockMDS/files/MockMDS/DeviceInfoIIR.txt
MockMDS/files/MockMDS/DiscoverFACE.txt
MockMDS/files/MockMDS/DiscoverFIR.txt
MockMDS/files/MockMDS/DiscoverIIR.txt
MockMDS/files/MockMDS/discoverInfo.txt
MockMDS/pom.xml
MockMDS/src/main/java/org/biometric/provider/CaptureRequest.java
MockMDS/src/main/java/org/biometric/provider/DiscoverRequest.java
MockMDS/src/main/java/org/biometric/provider/InfoRequest.java

updated readme, corrected discover request to send unsigned digitalId and device status

updated readme

---

mock-abis/pom.xml

Changes in pom to add SCM details

---

mock-sdk/src/main/java/io/mosip/mock/sdk/impl/SampleSDK.java

MOSIP-10045 : fixed sample and gallery success check for sample elements

---

MockMDS/Biometric Devices/Face/DigitalId.json
MockMDS/src/main/java/io/mosip/mock/sbi/devicehelper/SBIDeviceHelper.java
MockMDS/src/main/java/io/mosip/mock/sbi/service/SBIMockService.java
MockMDS/src/main/java/io/mosip/mock/sbi/service/SBIServiceResponse.java
MockMDS/src/main/java/io/mosip/registration/mdm/dto/StreamingRequestDetail.java

The device subtype should be "Full face" as per MDS.

MOSIP-10692

---

MockMDS/src/main/java/org/biometric/provider/JwtUtility.java

Fixed loading of properties from external properties file for auth capture

---

mock-abis/src/main/java/io/mosip/proxy/abis/CryptoCoreUtil.java
mock-abis/src/main/java/io/mosip/proxy/abis/service/impl/ProxyAbisInsertServiceImpl.java

Prependthumbprint changes

---

MockMDS/.gitignore
MockMDS/src/main/java/io/mosip/mock/sbi/service/SBIResponseInfo.java
MockMDS/src/main/java/io/mosip/mock/sbi/service/SBIWorker.java

Merge to main master

---

MockMDS/src/main/java/io/mosip/mock/sbi/service/SBIJsonInfo.java
MockMDS/src/main/java/io/mosip/mock/sbi/service/SBIServiceResponse.java

Modified SBIJsonInfo.java and SBIServiceResponse.java for Response Error Messages For Discovery and DeviceInfo Request
for device not connected
[
{
"error":{
"errorCode":"503",
"errorInfo":"Devices are not Connected, please connect devices"
}
}
]

Response Error Messages For Discovery and DeviceInfo Request

---

MockMDS/src/main/java/io/mosip/mock/sbi/service/SBIServiceResponse.java
MockMDS/src/main/java/org/biometric/provider/CryptoUtility.java

Modified SBIServiceResponse.java [For Thumbprint Bug and hash Changes… using bioValue] and CryptoUtility.java [Dateformat changes yyyy-mm-dd'T'HH:MM:ss'Z']

Modified SBIServiceResponse.java and CryptoUtility.java 

---

MockMDS/pom.xml
MockMDS/src/main/java/io/mosip/mock/sbi/service/SBIServiceResponse.java

Pom.xml changed for latest bcprov-jdk16, org.codehaus.jackson and SBIServiceResponse.java changed for HASH calculation and Biometric Count Bug

Pom.xml and SBIServiceResponse.java changed

---

MockMDS/src/main/java/io/mosip/mock/sbi/service/SBIServiceResponse.java

MOSIP-16471 stream issue fixed

---

mock-abis/src/main/java/io/mosip/proxy/abis/CryptoCoreUtil.java
mock-abis/src/main/java/io/mosip/proxy/abis/controller/ProxyAbisController.java
mock-abis/src/main/java/io/mosip/proxy/abis/service/impl/ProxyAbisInsertServiceImpl.java

MOSIP-19175 MockAbis certificate and CbeffValidator issue fixed

---

mock-sdk/pom.xml
mock-sdk/src/main/java/io/mosip/mock/sdk/service/CheckQualityService.java
mock-sdk/src/main/java/io/mosip/mock/sdk/service/SDKService.java

1.2.0.1-SNAPSHOT to 1.2.1-SNAPSHOT

version changed build failure

---

mock-sdk-jpeg-extractor/pom.xml
mock-sdk-jpeg-extractor/src/main/java/io/mosip/mock/sdk/jpeg/impl/BioSDKWithJpegExtractor.java

Bug fixes and Pom.xml changes from 0.9 version to latest for kernel.biometricsdk.version

Bug fixes and Pom.xml changes

---

mock-abis/pom.xml
mock-abis/src/main/java/io/mosip/proxy/abis/Listener.java
mock-abis/src/main/java/io/mosip/proxy/abis/ProxyAbisApplication.java
mock-abis/src/main/java/io/mosip/proxy/abis/controller/ProxyAbisController.java
mock-abis/src/main/java/io/mosip/proxy/abis/dto/Expectation.java
mock-abis/src/main/java/io/mosip/proxy/abis/dto/FailureResponse.java
mock-abis/src/main/java/io/mosip/proxy/abis/dto/IdentityRequest.java
mock-abis/src/main/java/io/mosip/proxy/abis/dto/IdentityResponse.java
mock-abis/src/main/java/io/mosip/proxy/abis/dto/InsertRequestMO.java
mock-abis/src/main/java/io/mosip/proxy/abis/dto/MockAbisQueueDetails.java
mock-abis/src/main/java/io/mosip/proxy/abis/dto/RequestMO.java
mock-abis/src/main/java/io/mosip/proxy/abis/dto/ResponseMO.java
mock-abis/src/main/java/io/mosip/proxy/abis/exception/ExceptionInterceptor.java
mock-abis/src/main/java/io/mosip/proxy/abis/exception/FailureReasonsConstants.java
mock-abis/src/main/java/io/mosip/proxy/abis/service/impl/ProxyAbisInsertServiceImpl.java

a) Mock ABIS changes to handle CTK test cases
b) Duplicate packet is rejected by ABIS although flag is FALSE

MOSIP-27456 and MOSIP-27576

---

mock-abis/src/main/java/io/mosip/proxy/abis/dao/ProxyAbisBioDataRepository.java
mock-abis/src/main/java/io/mosip/proxy/abis/dao/ProxyAbisInsertRepository.java
mock-abis/src/main/java/io/mosip/proxy/abis/entity/BiometricData.java
mock-abis/src/main/java/io/mosip/proxy/abis/entity/InsertEntity.java
mock-abis/src/main/java/io/mosip/proxy/abis/service/impl/ProxyAbisInsertServiceImpl.java

CTK Test case Abis-3028
to check if referenceId not found (in ABIS) in Gallery throw error 12

MOSIP-27456

---

mock-sdk/pom.xml

Reverts mosip/mosip-mock-services#297

Revert "MOSIP-28840"

---

.gitignore
MockMDS/pom.xml
mock-sdk-jpeg-extractor/pom.xml
mock-sdk/pom.xml

Had Pom.xml issue because of confusion .. have updated to the latest release branch . tested locally

[MOSIP-29978, MOSIP-30342, ES-480]

---

MockMDS/src/main/java/io/mosip/mock/sbi/service/SBIServiceResponse.java
MockMDS/src/main/java/io/mosip/registration/mdm/dto/BioMetricsDataDto.java
MockMDS/src/main/java/io/mosip/registration/mdm/dto/NewBioAuthDto.java
MockMDS/src/main/java/io/mosip/registration/mdm/dto/NewBioDto.java
MockMDS/src/main/java/org/biometric/provider/CaptureRequest.java

The attributes requestedScore and qualityScore should be floating point numbers with return type String

[MOSIP-31258] 

---

MockMDS/src/main/java/io/mosip/mock/sbi/service/SBIServiceResponse.java

For face biosubtype can be null for auth request in mock-mds

[MOSIP-32136]

---

.github/workflows/push-trigger.yml
MockMDS/pom.xml
MockMDS/run.sh
MockMDS/run_auth.bat
MockMDS/run_reg.bat
MockMDS/src/main/java/io/mosip/mock/sbi/service/SBIServiceResponse.java
MockMDS/src/main/java/org/biometric/provider/CORSManager.java
MockMDS/src/main/java/org/biometric/provider/CaptureRequest.java
MockMDS/src/main/java/org/biometric/provider/CryptoUtility.java
MockMDS/src/main/java/org/biometric/provider/DiscoverRequest.java
MockMDS/src/main/java/org/biometric/provider/InfoRequest.java
MockMDS/src/main/java/org/biometric/provider/StreamRequest.java
MockMDS/src/main/java/org/biometric/provider/WebAppInitializer.java
mock-abis/pom.xml
mock-abis/src/main/java/io/mosip/proxy/abis/Listener.java
mock-abis/src/main/java/io/mosip/proxy/abis/QueueListener.java
mock-mv/pom.xml
mock-mv/src/main/java/io/mosip/mock/mv/queue/Listener.java
mock-mv/src/main/java/io/mosip/mock/mv/queue/QueueListener.java
mock-sdk/pom.xml

a) javax.servlet-api  changed to jakarta.servlet-api.
b)  javax.jms-api  changed to jakarta.jms-api.

[MOSIP-32456, MOSIP-31258]

---

.github/workflows/push-trigger.yml

Testing sonar single-module and multi-module changes.

[MOSIP-42148]Update push-trigger.yml
